apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: registry-credential
    namespace: test
spec:
    refreshInterval: 3600s
    secretStoreRef:
        kind: SecretStore
        name: doppler-secret-store
    target:
        name: gitlab-registry-credential
        template:
            type: kubernetes.io/dockerconfigjson
            data:
                .dockerconfigjson: |
                    {
                      "auths": {
                        "{{ .registry }}": {
                          "username": "{{ .username }}",
                          "password": "{{ .password }}",
                          "email": "{{ .registryEmail }}",
                          "auth": "{{ list .username .password | join ":" | b64enc }}"
                        }
                      }
                    }
    data:
        - secretKey: registry
          remoteRef:
              key: GITLAB_REGISTRY_HOST
        - secretKey: registryEmail
          remoteRef:
              key: GITLAB_REGISTRY_EMAIL
        - secretKey: username
          remoteRef:
              key: GITLAB_DEPLOY_TOKEN_USERNAME
        - secretKey: password
          remoteRef:
              key: GITLAB_DEPLOY_TOKEN_PASSWORD
