apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: doppler-secret-store
    namespace: test
spec:
    provider:
        doppler:
            auth:
                secretRef:
                    dopplerToken:
                        name: doppler-auth-token
                        key: dopplerToken
